### ISSUE TITLE
Android Integration issue

### ISSUE THREAD

**Issue by Ankit-Shukla** [Beaconstac/Android-SDK#2]
There was an upgrade to the Beacon SDK which was launched some time ago and that is causing some issues when we are trying to integrate the SDK and run the sample.

Below is the error log, can you please look and advise:

01-14 14:09:27.625 30370-30370/? I/art: Late-enabling -Xcheck:jni
01-14 14:09:27.699 30370-30370/com.mobstac.beaconstacexample W/System: ClassLoader referenced unknown path: /data/app/com.mobstac.beaconstacexample-2/lib/arm
01-14 14:09:27.738 30370-30392/com.mobstac.beaconstacexample I/GMPM: App measurement is starting up
01-14 14:09:27.743 30370-30392/com.mobstac.beaconstacexample E/GMPM: getGoogleAppId failed with status: 10
01-14 14:09:27.744 30370-30392/com.mobstac.beaconstacexample E/GMPM: Uploading is not possible. App measurement disabled
01-14 14:09:27.802 30370-30370/com.mobstac.beaconstacexample I/Crittercism: Initializing Crittercism 5.0.6 for App ID 55828d0b880e1802279cfe77
01-14 14:09:27.894 30370-30370/com.mobstac.beaconstacexample D/Volley: [1] DiskBasedCache.clear: Cache cleared.
01-14 14:09:27.895 30370-30370/com.mobstac.beaconstacexample D/Volley: [1] DiskBasedCache.clear: Cache cleared.
01-14 14:09:27.997 30370-30439/com.mobstac.beaconstacexample D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
01-14 14:09:28.050 30370-30439/com.mobstac.beaconstacexample I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (I8a1ccf9ecb)
01-14 14:09:28.050 30370-30439/com.mobstac.beaconstacexample I/Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.06.00.01
01-14 14:09:28.050 30370-30439/com.mobstac.beaconstacexample I/Adreno-EGL: Build Date: 11/02/15 Mon
01-14 14:09:28.050 30370-30439/com.mobstac.beaconstacexample I/Adreno-EGL: Local Branch: workspace
01-14 14:09:28.050 30370-30439/com.mobstac.beaconstacexample I/Adreno-EGL: Remote Branch:
01-14 14:09:28.050 30370-30439/com.mobstac.beaconstacexample I/Adreno-EGL: Local Patches:
01-14 14:09:28.050 30370-30439/com.mobstac.beaconstacexample I/Adreno-EGL: Reconstruct Branch:
01-14 14:09:28.052 30370-30439/com.mobstac.beaconstacexample I/OpenGLRenderer: Initialized EGL, version 1.4
01-14 14:09:29.726 30370-30433/com.mobstac.beaconstacexample E/Volley: [5080] BasicNetwork.performRequest: Unexpected response code 403 for https://beaconstac.mobstac.com/api/1.0/places/?organization=0
01-14 14:09:29.746 30370-30370/com.mobstac.beaconstacexample D/Volley: [1] 3.onErrorResponse: MSPlace
01-14 14:09:29.749 30370-30407/com.mobstac.beaconstacexample E/Volley: [5069] BasicNetwork.performRequest: Unexpected response code 403 for https://beaconstac.mobstac.com/api/1.0/rules/?organization=0&page=1
01-14 14:09:29.762 30370-30370/com.mobstac.beaconstacexample E/Beaconstac ERROR: Error syncing geofence
01-14 14:09:29.762 30370-30370/com.mobstac.beaconstacexample E/Beaconstac ERROR: Server Error

Thanks,
Ankit

**Comment by vibinvarghesemobstac** [comment]
If you notice towards, the end of the log, the url request is not as per requirement.

https://beaconstac.mobstac.com/api/1.0/rules/?organization=0&page=1

The organization is being passed as '0'. That is the reason you are facing issues.

You will have to specify the organization and the developer token in the beaconstac.xml file.

Hope this resolves your issues.
