### ISSUE TITLE
What Redeem in Media Card

### ISSUE THREAD

**Issue by Ankit-Shukla** [Beaconstac/Android-SDK#3]
Hi,

We have implemented Beacon on Android and iPhone both, to recieve cards on iPhone we get JSON and on android we get action list, now when we approach near a beacon we can see the cards in form of pop up but the action written below the card is not shown, for eg. in Photo card there are two actions for user "Dismiss and Redeem" how do we get these action and how does it work? Similarly for Media card there is option to "Dismiss and Watch" which we are not getting in response? As of now we have created custom lable/action button "View and Cancel" but shall this not be something that we should get directly from Beacon based on the action associated with each card?

Please advise.

Thanks,
Ankit

**Comment by vibinvarghesemobstac** [comment]
Hi Ankit,

The buttons under the media and photo cards that are visible are the configured under the call to action section of the manage.beaconstac.com portal.


To retrieve this data on android please use the following snippet of code.

This will be available in the sample app on the github repository soon.
messageMap = action.getMessage();

To retrieve the Call to Action Label use : messageMap.get("notificationOkLabel");

To retrieve the Call to Action Link use : messageMap.get("notificationOkAction");


Do let us know if you require any further assistance.
